// <auto-generated />
using CamisasApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CamisasApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CamisasApi.Models.Camisas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tamanho")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Camisas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Classe = 1,
                            Nome = "Corinthians",
                            Tamanho = "GG",
                            Valor = 500m
                        },
                        new
                        {
                            Id = 2,
                            Classe = 2,
                            Nome = "Palmeiras",
                            Tamanho = "P",
                            Valor = 50m
                        },
                        new
                        {
                            Id = 3,
                            Classe = 0,
                            Nome = "Vasco",
                            Tamanho = "G",
                            Valor = 150m
                        },
                        new
                        {
                            Id = 4,
                            Classe = 1,
                            Nome = "São Paulo",
                            Tamanho = "M",
                            Valor = 250m
                        },
                        new
                        {
                            Id = 5,
                            Classe = 2,
                            Nome = "Santos",
                            Tamanho = "GG",
                            Valor = 70m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
